# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediant',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingrediants',
            field=models.ManyToManyField(to='recipe.Ingrediant'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.RecipeImage', verbose_name='Recipe images'),
        ),
    ]
