# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20160330_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=15)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Ingrediant')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingrediants',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='ingrediant',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Unit'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingrediant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.RecipeIngredient'),
            preserve_default=False,
        ),
    ]
