# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20160330_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='ingrediant',
            name='spice_type',
            field=models.CharField(choices=[('0', 'Neutral'), ('solt', 'Solt'), ('sugar', 'Sugar'), ('bitter', 'Bitter'), ('acid', 'Acid')], default='0', max_length=30),
        ),
    ]
