# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20160330_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingrediant',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingrediant',
            field=models.ManyToManyField(to='recipe.RecipeIngredient'),
        ),
    ]
