# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20160330_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='independet_author',
            new_name='independent_author',
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
