# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20160331_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'included ingredient'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingrediant',
            new_name='ingredient',
        ),
    ]
