# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20160331_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['ingredient'], 'verbose_name': 'included ingredient'},
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('0', 'Choose measure unit...'), ('gramm', 'g'), ('dekagramm', 'dkg'), ('kilogramm', 'kg'), ('tea_spun', 'Tea spun'), ('table_spun', 'Table spun'), ('quantity', 'quantity'), ('piece', 'piece')], default='0', max_length=20),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
