# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20160407_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='images/recipes/'),
        ),
    ]
